# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "dwc:datasetID", # <pcg_extract_fow>
  "datasetID", # <pcg_extract_fow>
  "scientificNameID", # <pcg_extract_fow>
  "taxonRank", # <pcg_extract_fow>
  "scientificName", # <pcg_extract_fow>
  "taxonID", # <pcg_extract_fow>
  NULL
))
